### ISSUE TITLE
باگ در آپدیت جدید فلاتر

### ISSUE THREAD

**Issue by sepehr13494** [M-amir-M/persian-datetime-picker#15]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/persian_datetime_picker-1.0.7/lib/widget/dialog.dart:725:45: Error: No named parameter with the name 'shadowThemeOnly'.
  final ThemeData theme = Theme.of(context, shadowThemeOnly: true);

/C:/src/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^

موقع بیلد گرفتن این ارور رو میده

**Comment by M-amir-M** [comment]
Fixed!
