### ISSUE TITLE
باگ در ساعت

### ISSUE THREAD

**Issue by mma-amini** [M-amir-M/persian-datetime-picker#17]
مقدار ساعت از ۰ تا ۲۳ هست. شما مقدار ۲۴ رو هم گذاشتید که اشتباه هست. الان هم میشه مقدار
۰:۱۰
رو انتخاب کرد و هم میشه مقدار
۲۴:۱۰
رو انتخاب کرد.

**Comment by M-amir-M** [comment]
در نسخه جدید برطرف شده
