### ISSUE TITLE
Show the name of month, not the number of that

### ISSUE THREAD

**Issue by ahazizzadeh** [M-amir-M/persian-datetime-picker#31]
![image](https://user-images.githubusercontent.com/64953329/139669639-1443e132-7f79-4d72-9f50-8d59f45883af.png)
لطفا مثل نسخه خارجی، به جای شماره ماه، اسم آن را در محل انتخاب سال، نمایش بدهید (یا امکان انتخاب نوع نمایش را برای کاربر قرار دهید)

**Comment by M-amir-M** [comment]
The new version now supports this feature. Thanks for your input!
