### ISSUE TITLE
Please provide a donation link for this awesome project

### ISSUE THREAD

**Issue by AliRezaBeitari** [M-amir-M/persian-datetime-picker#39]
Hi.

I'm really glad that I found this project. It saved a lot of time and work for my last project. I first thank a lot for this wonderful library and kindly ask for a donation link so that I can at least appreciate your work and time in the slightest way.

Thanks again.

**Comment by M-amir-M** [comment]
سلام و درود 
حقیقتا نمیخواستم لینک دونیت قرار بدم چون میدونم چیزی که دونیت میشه خیلی اندک هست.
ولی به ذهنم رسید که این مبالغ اندک برای خیلی از نیازمندان کمک بزرگی هست و تصمیم گرفتم مبالغی که دونیت میشه رو به نیازمندان پرداخت کنم.

**Comment by AliRezaBeitari** [comment]
تشکر کوچک و ناقابلی بابت تلاش های شما

![Uploading 20220625_125225.jpg…]()

**Comment by AliRezaBeitari** [comment]
تشکر کوچک و ناقابلی بابت تلاش های شما

![20220625_125225](https://user-images.githubusercontent.com/21037809/175765201-26e9e47a-4f01-48c7-bfe9-460161c080bf.jpg)
