### ISSUE TITLE
بستن یک تاریخ خاص

### ISSUE THREAD

**Issue by elyasbeshkani** [M-amir-M/persian-datetime-picker#5]
سلام
ببخشید من میخواستم یه سری روزهای خاص رو ببندم
مثلا بگم پنج شنبه و جمع یا مثلا یه روز خاص رو نشه انتخاب کرد
ممنون میشم راهنمایی کنید کجاشو باید تغییر بدم
تشکر

**Comment by M-amir-M** [comment]
از disable استفاده کنید.
داکیومنت رو بخونید

**Comment by Ham3D** [comment]
توضیحات کامل نیست
داکیومنت رو از کجا میتونم ببینم ؟

**Comment by alireza2281** [comment]
از طریق لینک زیر میتونید یه سری روز رو غیرفعال کنید
https://pub.dev/documentation/persian_datetime_picker/latest/datetimepicker/PSelectableDayPredicate.html
