### ISSUE TITLE
How to make a time picker for 24 hours format?

### ISSUE THREAD

**Issue by majidebraa** [M-amir-M/persian-datetime-picker#53]
How to make a time picker for 24 hours format?

**Comment by M-amir-M** [comment]
Try this

`
var picked = await showPersianTimePicker(
  context: context,
  initialTime: TimeOfDay.now(),
  builder: (BuildContext context, Widget child) {
    return Directionality(
      textDirection: TextDirection.rtl,
      child: MediaQuery(
        data: MediaQuery.of(context).copyWith(alwaysUse24HourFormat: true),
        child: child,
      ),
    );
  },
);
`
