### ISSUE TITLE
not show the last number of year in PCupertinoDatePickerMode.date

### ISSUE THREAD

**Issue by mreza-mohammadzadeh** [M-amir-M/persian-datetime-picker#55]
hello, I find a bug in the package persian_datetime_picker when using the mode: PCupertinoDatePickerMode.date
DateException: Jalali day is out of valid range.
and not show the last number of year

**Comment by vieramason** [comment]
![Screenshot 1402-10-06 at 12 36 10](https://github.com/M-amir-M/persian-datetime-picker/assets/55649798/d407b283-b82b-4a4d-a9f5-d75ccf210b99)
I have same issue.

**Comment by M-amir-M** [comment]
You can fix this issue by changing the font size in the Theme.
