### ISSUE TITLE
Jalali day is out of valid range

### ISSUE THREAD

**Issue by shahpasandar** [M-amir-M/persian-datetime-picker#56]
It happens in every 30th day of each month (of second half of the year that the months have 30 days) when I call the following:
`Jalali.now().add(days: 1)`

**Comment by mmohammadmfallahm02** [comment]
This issue is not related to the package. You can use the addDays method to solve it:
`Jalali newDate = Jalali.now().addDays(1);`

**Comment by basicFlutter** [comment]
سلام ممنونم بابت پکیج خوبتون 
مشکلی که وجود داره تاریخ 31 هر ماه این ارور رو میده
DateException: Jalali day is out of valid range.

**Comment by M-amir-M** [comment]
This issue has been solved in the latest version.
