### ISSUE TITLE
how can make cusomize ?

### ISSUE THREAD

**Issue by AbbasHoseini** [M-amir-M/persian-datetime-picker#57]
سلام راهی هست بشه این تقویم رو سفارشی سازی کرد؟ رنگ و استایلش رو

**Comment by Sajad-Ghorbani** [comment]
سلام با استفاده از builder میتونید هر تغییری که خواستید انجام بدید.
`builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: ColorScheme.light(
              primary: Colors.yellow, // header background color
              onPrimary: Colors.black, // header text color
              onSurface: Colors.green, // body text color
            ),
            textButtonTheme: TextButtonThemeData(
              style: TextButton.styleFrom(
                foregroundColor: Colors.red, // button text color
              ),
            ),
          ),
          child: child!,
        );
      },`

**Comment by Asncodes-80** [comment]
> سلام با استفاده از بیلدر میتونید هر تغییری که خواستید انجام بدید. builder: (context, child) { return Theme( data: Theme.of(context).copyWith( colorScheme: ColorScheme.light( primary: Colors.yellow, // header background color onPrimary: Colors.black, // header text color onSurface: Colors.green, // body text color ), textButtonTheme: TextButtonThemeData( style: TextButton.styleFrom( foregroundColor: Colors.red, // button text color ), ), ), child: child!, ); },

How I can change typography sizes? I apply my customized `themeData` over this widget, but text doesn't have any size change!
