### ISSUE TITLE
خطای کد با اپدیت فلاتر

### ISSUE THREAD

**Issue by masdercoder** [M-amir-M/persian-datetime-picker#59]
سلام
وقت بخیر
متاسفانه با اپدیت فلاتر یک خطا در این پکیج ایجاد شده که ممنون میشم بررسی بشه
/C:/Users/Masder/AppData/Local/Pub/Cache/hosted/pub.dev/persian_datetime_picker-2.5.0/lib/src/pdate_picker_deprecated.dart:268:33: Error: The getter 'accentTextTheme' isn't defined for the class 'ThemeData'.
- 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('/I:/flutter/packages/flutter/lib/src/material/theme_data.dart').
theme_data.dart:1
Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentTextTheme'.
          itemStyle = themeData.accentTextTheme.bodyText1;

**Comment by AmirhosseinShk** [comment]
we have same problem please fix this!

**Comment by AmirhosseinShk** [comment]
I'm fixing this issue and creating a pull request, please check it and merge it.
https://github.com/M-amir-M/persian-datetime-picker/pull/61

**Comment by sanazmrz** [comment]
Still there is a problem with ThemeData, any update ?
