### ISSUE TITLE
Flushbar bug! refuses builing app

### ISSUE THREAD

**Issue by alizera** [M-amir-M/persian-datetime-picker#6]
Thanks for nice lib, but using flushbar inside project causes [this error](https://github.com/AndreHaueisen/flushbar/issues/110)!
Please use snackBar if it's possible.

**Comment by alitorki2651** [comment]
منم این مشکلو دارم چطوری فیکسش کنم؟

**Comment by elyasbeshkani** [comment]
@M-amir-M 
Thanks for good package.
please fix this bug as soon as you can
i need this for my projects.
thanks a lot.

**Comment by DhruvamSharma** [comment]
I am still able to see this error. Has anyone been able to fix it?

**Comment by elyasbeshkani** [comment]
> I am still able to see this error. Has anyone been able to fix it?

Unfortunately, I also have an error,too

**Comment by M-amir-M** [comment]
This issue fixed.please install last version. @elyasbeshkani @alizera @DhruvamSharma
