### ISSUE TITLE
CupertinoTimePicker(): LateInitializationError: Field 'localizations' has not been initialized.

### ISSUE THREAD

**Issue by kiannrezaa** [M-amir-M/persian-datetime-picker#72]
I try to use CupertinoTimerPicker as a Widget in my bottom sheet, but the following is thrown:

> The following LateError was thrown building CupertinoTimerPicker(dirty, dependencies: [Directionality, _InheritedCupertinoTheme], state: _CupertinoTimerPickerState#816fa):
> LateInitializationError: Field 'localizations' has not been initialized.

Using the default CupertinoTimerPicker provided by 'package:flutter/cupertino.dart' works just fine. I just wanted the Persian support in my app.

This is the part causing the error:

`CupertinoTimerPicker(
                onTimerDurationChanged: (duration) {)`

**Comment by M-amir-M** [comment]
@kiannrezaa This issue has been solved in the latest version.
