### ISSUE TITLE
خطا در فلاتر 3.22

### ISSUE THREAD

**Issue by mma-amini** [M-amir-M/persian-datetime-picker#82]
سلام و وقت بخیر
در آخرین نسخه فلاتر لایبراری این خطا رو میده:
/pub.dev/persian_datetime_picker-2.6.0/lib/src/pcalendar_date_range_picker.dart:761:29: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/F:/sdk/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
      itemStyle = textTheme.bodyText2?.apply(color: colorScheme.onPrimary);
                            ^^^^^^^^^
لطفا بررسی کنید. ممنون

**Comment by mustafa-fahimi** [comment]
> سلام و وقت بخیر در آخرین نسخه فلاتر لایبراری این خطا رو میده: /pub.dev/persian_datetime_picker-2.6.0/lib/src/pcalendar_date_range_picker.dart:761:29: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
> 
> * 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/F:/sdk/flutter/packages/flutter/lib/src/material/text_theme.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
>   itemStyle = textTheme.bodyText2?.apply(color: colorScheme.onPrimary);
>   ^^^^^^^^^
>   لطفا بررسی کنید. ممنون

Duplicate of [https://github.com/M-amir-M/persian-datetime-picker/issues/78](url)
