### ISSUE TITLE
How to select multiple dates (not range)

### ISSUE THREAD

**Issue by yazdanMhmmdi** [M-amir-M/persian-datetime-picker#83]
is there any way to select multiple dates from date picker? (not range) for example:
03-04-01
03-04-03
03-04-05

**Comment by M-amir-M** [comment]
@yazdanMhmmdi Currently, the default Flutter `showPersianDatePicker` doesn't support selecting multiple individual dates (non-range).

**Comment by iceberg1369** [comment]
we need this
