### ISSUE TITLE
آپدیت به متریال ۳

### ISSUE THREAD

**Issue by ZhiaDev** [M-amir-M/persian-datetime-picker#88]
سلام وقتتون بخیر باشه
اولا تشکر میکنم بابت بکیج خفنی که ساختید، من که در پروژه هام استفاده میکنم و همیشه کیف میکنم از استفادش

فقط این پروژه آخرم کامل روی دیزاین سیستم متریال ۳ داره جلو میره و دیزاین فعلی این Date Picker بهش نمیخوره و خیلی قدیمی به نظر میرسه، آیا در نظر دارید آپدیتی براش منتشر کنید که دیزاینش سازگار بشه با متریال ۳ (همانند دیگر ویجت های فلاتر)؟

[DatePicker Material 3](https://m3.material.io/components/date-pickers/overview#0e162323-24e9-4fef-9dd7-9e86dfc1f9bd)

**Comment by M-amir-M** [comment]
@ZhiaDev 
درود بر شما 
بسیار خوشحالیم که مورد استفاده قرار گرفته.
به زودی در نسخه جدید از متریال ۳ ساپورت خواهد کرد.
و همچنین در این نسخه قابلیت شخصی سازی بسیار بالایی نسبت به نسخه های قبل خواهد داشت.

**Comment by M-amir-M** [comment]
The new version now supports Material 3. Thanks for your input!
