### ISSUE TITLE
Georgian Date Shown As Jalali Date

### ISSUE THREAD

**Issue by mohamadkenway** [M-amir-M/persian-datetime-picker#90]
Georgian date show as Jalali date after calling 
showPersianDatePicker(
      context: context,
      initialDate: date_picker.Jalali.now(),
      firstDate: date_picker.Jalali.now(),
      lastDate: date_picker.Jalali(1450, 9),
    );
![Screenshot from 2024-11-19 12-46-00](https://github.com/user-attachments/assets/72602ca4-b6c5-4b99-9aca-be25bec8fef0)

**Comment by ialirezairanmanesh** [comment]
Same problem here...

**Comment by M-amir-M** [comment]
Add localizationsDelegates like the documentation...

```dart
    return MaterialApp(
      title: 'Date and Time Pickers',
      locale: const Locale("fa", "IR"),
      supportedLocales: const [
        Locale("fa", "IR"),
        Locale("en", "US"),
      ],
      localizationsDelegates: const [
        // Add Localization
        PersianMaterialLocalizations.delegate,
        PersianCupertinoLocalizations.delegate,
        // DariMaterialLocalizations.delegate, Dari
        // DariCupertinoLocalizations.delegate,
        // PashtoMaterialLocalizations.delegate, Pashto
        // PashtoCupertinoLocalizations.delegate,
        // SoraniMaterialLocalizations.delegate, Kurdish
        // SoraniCupertinoLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      ...
    );
```

**Comment by mohamadkenway** [comment]
> ```dart
> return MaterialApp(
>       title: 'Date and Time Pickers',
>       locale: const Locale("fa", "IR"),
>       supportedLocales: const [
>         Locale("fa", "IR"),
>         Locale("en", "US"),
>       ],
>       localizationsDelegates: const [
>         // Add Localization
>         PersianMaterialLocalizations.delegate,
>         PersianCupertinoLocalizations.delegate,
>         // DariMaterialLocalizations.delegate, Dari
>         // DariCupertinoLocalizations.delegate,
>         // PashtoMaterialLocalizations.delegate, Pashto
>         // PashtoCupertinoLocalizations.delegate,
>         // SoraniMaterialLocalizations.delegate, Kurdish
>         // SoraniCupertinoLocalizations.delegate,
>         GlobalMaterialLocalizations.delegate,
>         GlobalWidgetsLocalizations.delegate,
>         GlobalCupertinoLocalizations.delegate,
>       ],
>       ...
>     );
> ```

not worked for me

**Comment by mohamadkenway** [comment]
as this image show, there is a bug due showing persian years and button show georgian date

![Screenshot_20241211_103440](https://github.com/user-attachments/assets/462016b0-bfd8-4bdc-8143-9ead1f139691)

**Comment by hosseinshaya** [comment]
Same problem here... And I saw an analysis issue on package on pub.dev.
Maybe problem is on newer flutter version.

**Comment by M-amir-M** [comment]
@hosseinshaya @mohamadkenway @ialirezairanmanesh 

Have you tried running the example project? Does the same issue occur there as well?

**Comment by M-amir-M** [comment]
Since no further issues have been reported regarding this problem, I am closing this issue. If the problem persists, feel free to reopen it or create a new issue.

**Comment by Masishta** [comment]
The problem still exists.
I use this config:

        localizationsDelegates: const [
          AppLocalizations.delegate,
          PersianMaterialLocalizations.delegate,
          PersianCupertinoLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        supportedLocales: const [
          Locale('fa', 'IR'),
          Locale('en', 'US'),
        ],

<img width="285" alt="image" src="https://github.com/user-attachments/assets/42a2ed04-b37a-4936-8132-26e2cd126548" />
