### ISSUE TITLE
خطا در نسخه 3.27 فلاتر DialogThemeData

### ISSUE THREAD

**Issue by yaser-p** [M-amir-M/persian-datetime-picker#92]
با عرض سلام وخسته نباشید
در فلاتر نسخه 3.27 پکیج خطای زیر رو داره:
 Error: A value of type 'DialogThemeData' can't be assigned to a variable of type 'DialogTheme'.
ممنون میشم بررسی بفرمایید.با تشکر

**Comment by sebastiankan** [comment]
درسته بعد از آپدیت به ورژن ۳.۲۷ این اررور رو میده

**Comment by fodedoumbouya** [comment]
https://github.com/M-amir-M/persian-datetime-picker/pull/94

**Comment by M-amir-M** [comment]
درود
در پول ریکویست https://github.com/M-amir-M/persian-datetime-picker/pull/93 این موضوع برطرف شده
