### ISSUE TITLE
Error: 'DialogThemeData' isn't a type

### ISSUE THREAD

**Issue by fakhravari** [M-amir-M/persian-datetime-picker#96]
Flutter 3.24.5 
Dart 3.5.4 
DevTools 2.37.3

/C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/persian_datetime_picker-3.1.0/lib/src/material/date_picker.dart:687:11: Error: 'DialogThemeData' isn't a type.
    final DialogThemeData dialogTheme = theme.dialogTheme;
          ^^^^^^^^^^^^^^^
/C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/persian_datetime_picker-3.1.0/lib/src/material/date_picker.dart:1632:15: Error: 'DialogThemeData' isn't a type.
        final DialogThemeData dialogTheme = theme.dialogTheme;
              ^^^^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception

**Comment by M-amir-M** [comment]
@fakhravari 
If you are using Flutter version 3.7 or later, use version 3.1.0 of the package. For Flutter versions earlier than 3.7, use version 3.0.2 of the package.
